### ISSUE TITLE
Using Karabiner to open applications

### ISSUE THREAD

**Issue by DandyDev** [nikitavoloboev/dotfiles#21]
Hi @nikitavoloboev!

First of all, I want to say that it is awesome that you're sharing so much knowledge with the world. After finding https://github.com/nikitavoloboev/my-mac-os I discovered your wiki and I've been reading bits and pieces of it. It's especially interesting how you've managed to automate everything in your Mac workflow. It inspired me to work on that too.

I do have one question about the way you use Karabiner. Looking at [your configuration](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/karabiner.edn), it seems you're using Keyboard Maestro for launching applications when pressing certain key combinations. My question to you is: why add the extra layer (KM) in between if you can also launch applications directly using AppleScript in Karabiner? I've created the following config which works just fine:

```clojure
{:templates {:alfred "osascript -e 'tell application \"Alfred 3\" to run trigger \"%s\" in workflow \"%s\" with argument \"\"'"
             :app "osascript -e 'tell application \"%s\" to activate'"
             :km "osascript -e 'tell application \"Keyboard Maestro Engine\" to do script \"%s\"'"}
 :simlayers {:w-mode {:key :w}}
 :main [{:des "alfred searches"
         :rules [[[:j :k] [:alfred "search google" "net.deanishe.alfred-searchio"]]]}
        {:des "launchers"
         :rules [:w-mode
                 [:c [:app "Chrome"]]
                 [:i [:app "iTerm"]]]}]
 }
```

I want to understand what the advantage is for using KM instead of AppleScript in this scenario :)

**Comment by nikitavoloboev** [comment]
I use KM to open apps because I get dual action on it:

![2018-10-06 at 11 47](https://user-images.githubusercontent.com/6391776/46569989-af994880-c95d-11e8-91b8-fa9328a075ae.png)

Switch to app if not active. Switch to previous app if active. 🙂

**Comment by DandyDev** [comment]
Great, that makes it clear. Thanks for the explanation!
