### ISSUE TITLE
Suggestion: check out chezmoi

### ISSUE THREAD

**Issue by twpayne** [nikitavoloboev/dotfiles#28]
### Feature ✨

Consider using https://github.com/twpayne/chezmoi - it's a generic dotfile manager written in Go but easy installation (no runtime dependencies) and will avoid all the custom code in `magefile.go`.

**Comment by nikitavoloboev** [comment]
Thanks. I have it starred but didn't look in depth into it. 

I used https://github.com/anishathalye/dotbot previously and decided to just roll my own solution rather than use some custom declarative config that I never remember. 

Thanks for making an awesome tool. ❤️

**Comment by twpayne** [comment]
Thanks for the kind words :) chezmoi only needs a config file if you want to set custom variables in templates.
